### ISSUE TITLE
[Bug]: AttributeError: module 'modules.devices' has no attribute 'cuda_ok' while opening sd webui in amd gpu rx6600

### ISSUE THREAD

**Issue by Hoxor99** [lshqqytiger/stable-diffusion-webui-amdgpu#488]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

it has been working recently until the new zluda update, then it started showing this error. i've tried to reinstall it too but didn't work

### Steps to reproduce the problem

1. Followed the steps that showed in the git
2. Installed zluda library and rocm librabry and followed the steps and added them to system variables
3. run webui with --use-zluda --medvram-sdxl --update-check --skip-ort args
4. error

### What should have happened?

i dont know

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

\

### Console logs

```Shell
venv "G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: v1.9.3-amd-29-g845d8590
Commit hash: 845d859043d561ef0bf27773be84d9e7a253c7ee
Using ZLUDA in C:\zluda
Skipping onnxruntime installation.
You are up to date with the most recent release.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --medvram-sdxl --update-check --skip-ort
Traceback (most recent call last):
  File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\launch.py", line 44, in main
    start()
  File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 689, in start
    import webui
  File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\webui.py", line 13, in <module>
    initialize.imports()
  File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\modules\shared_init.py", line 66, in initialize
    initialize_zluda()
  File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\modules\zluda.py", line 37, in initialize_zluda
    if not devices.cuda_ok or not is_zluda(device):
AttributeError: module 'modules.devices' has no attribute 'cuda_ok'
Press any key to continue . . .
```

### Additional information

Amd driver version 24.3.1

**Comment by lshqqytiger** [comment]
Fixed.
