### ISSUE TITLE
[Bug]: impossible to install ZLUDA (845d859)

### ISSUE THREAD

**Issue by EygenCat** [lshqqytiger/stable-diffusion-webui-amdgpu#489]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I was installing a new commit, and I couldn't commit it.

### Steps to reproduce the problem

Downloaded the commit using GIT [845d859](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/commit/845d859043d561ef0bf27773be84d9e7a253c7ee), launch arguments "set COMMANDLINE_ARGS= --autolaunch --use-zluda --theme=dark"

### What should have happened?

Installation

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-07-07-11-10.json](https://github.com/user-attachments/files/16118938/sysinfo-2024-07-07-11-10.json)

### Console logs

```Shell
Creating venv in directory H:\IL\zluda\stable-diffusion-webui-amdgpu\venv using python "C:\Users\Uzver\AppData\Local\Programs\Python\Python310\python.exe"
venv "H:\IL\zluda\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.3-amd-29-g845d8590
Commit hash: 845d859043d561ef0bf27773be84d9e7a253c7ee
Installing torch and torchvision
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.3.0
  Using cached https://download.pytorch.org/whl/cu118/torch-2.3.0%2Bcu118-cp310-cp310-win_amd64.whl (2673.0 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.18.1%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting networkx
  Using cached https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.3-py3-none-any.whl (133 kB)
Collecting mkl<=2021.4.0,>=2021.1.1
  Using cached https://download.pytorch.org/whl/mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
Collecting fsspec
  Using cached https://download.pytorch.org/whl/fsspec-2024.2.0-py3-none-any.whl (170 kB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting filelock
  Using cached https://download.pytorch.org/whl/filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting typing-extensions>=4.8.0
  Using cached https://download.pytorch.org/whl/typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.18.0%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting numpy
  Using cached https://download.pytorch.org/whl/numpy-1.26.3-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
Collecting tbb==2021.*
  Using cached https://download.pytorch.org/whl/tbb-2021.11.0-py3-none-win_amd64.whl (298 kB)
Collecting intel-openmp==2021.*
  Using cached https://download.pytorch.org/whl/intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: tbb, mpmath, intel-openmp, typing-extensions, sympy, pillow, numpy, networkx, mkl, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.5 filelock-3.13.1 fsspec-2024.2.0 intel-openmp-2021.4.0 jinja2-3.1.3 mkl-2021.4.0mpmath-1.3.0 networkx-3.2.1 numpy-1.26.3 pillow-10.2.0 sympy-1.12 tbb-2021.11.0 torch-2.3.0+cu118 torchvision-0.18.0+cu118 typing-extensions-4.9.0
WARNING: There was an error checking the latest version of pip.
Using ZLUDA in H:\IL\zluda\stable-diffusion-webui-amdgpu\.zluda
Installing clip
Installing open_clip
Cloning assets into H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-webui-assets...
Cloning into 'H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-webui-assets'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 0), reused 20 (delta 0), pack-reused 0
Receiving objects: 100% (20/20), 132.70 KiB | 1.34 MiB/s, done.
Cloning Stable Diffusion into H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai...
Cloning into 'H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (571/571), done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 580 (delta 278), reused 446 (delta 247), pack-reused 9
Receiving objects: 100% (580/580), 73.44 MiB | 19.62 MiB/s, done.
Resolving deltas: 100% (278/278), done.
Cloning Stable Diffusion XL into H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\generative-models...
Cloning into 'H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\generative-models'...
remote: Enumerating objects: 941, done.
remote: Total 941 (delta 0), reused 0 (delta 0), pack-reused 941Receiving objects:  91% (857/941), 32.79 MiB | 21.64 MiBReceiving objects:  98% (923/941), 32.79 MiB | 21.64 MiB/s
Receiving objects: 100% (941/941), 43.85 MiB | 22.45 MiB/s, done.
Resolving deltas: 100% (489/489), done.
Cloning K-diffusion into H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\k-diffusion...
Cloning into 'H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\k-diffusion'...
remote: Enumerating objects: 1345, done.
remote: Counting objects: 100% (1345/1345), done.
remote: Compressing objects: 100% (443/443), done.
remote: Total 1345 (delta 947), reused 1249 (delta 895), pack-reused 0
Receiving objects: 100% (1345/1345), 232.84 KiB | 1.26 MiB/s, done.
Resolving deltas: 100% (947/947), done.
Cloning BLIP into H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\BLIP...
Cloning into 'H:\IL\zluda\stable-diffusion-webui-amdgpu\repositories\BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 277 (delta 137), reused 136 (delta 135), pack-reused 112Receiving objects: 100% (277/277), 5.00 MiB | 9.93Receiving objects: 100% (277/277), 7.03 MiB | 12.02 MiB/s, done.

Resolving deltas: 100% (152/152), done.
Installing requirements
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
H:\IL\zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --autolaunch --use-zluda --listen --theme=dark 
H:\IL\zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\diffusers\models\vq_model.py:20: FutureWarning: `VQEncoderOutput` is deprecated and will be removed in version 0.31. Importing `VQEncoderOutput` from `diffusers.models.vq_model` is deprecated and this will be removed in a future version. Please use `from diffusers.models.autoencoders.vq_model import VQEncoderOutput`, instead.
  deprecate("VQEncoderOutput", "0.31", deprecation_message)
H:\IL\zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\diffusers\models\vq_model.py:25: FutureWarning: `VQModel` is deprecated and will be removed in version 0.31. Importing `VQModel` from `diffusers.models.vq_model` is deprecated and this will be removed in a future version. Please use `from diffusers.models.autoencoders.vq_model import VQModel`,instead.
  deprecate("VQModel", "0.31", deprecation_message)
ONNX: version=1.18.1 provider=CUDAExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
Traceback (most recent call last):
  File "H:\IL\zluda\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "H:\IL\zluda\stable-diffusion-webui-amdgpu\launch.py", line 44, in main
    start()
  File "H:\IL\zluda\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 689, in start
    import webui
  File "H:\IL\zluda\stable-diffusion-webui-amdgpu\webui.py", line 13, in <module>
    initialize.imports()
  File "H:\IL\zluda\stable-diffusion-webui-amdgpu\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "H:\IL\zluda\stable-diffusion-webui-amdgpu\modules\shared_init.py", line 66, in initialize
    initialize_zluda()
  File "H:\IL\zluda\stable-diffusion-webui-amdgpu\modules\zluda.py", line 37, in initialize_zluda
    if not devices.cuda_ok or not is_zluda(device):
AttributeError: module 'modules.devices' has no attribute 'cuda_ok'
Для продолжения нажмите любую клавишу . . .
```

### Additional information

Ryzen 5600X
32Gb ram
RX 6700 XT

**Comment by lshqqytiger** [comment]
Fixed.
