### ISSUE TITLE
[Bug]: Extensions are not working on the Zluda version of Stable diffsuion (RX6600)

### ISSUE THREAD

**Issue by Hoxor99** [lshqqytiger/stable-diffusion-webui-amdgpu#497]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Extensions are not working in the zluda version of stable diffsuion, Extensions are not installing, it shows this ""

GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git fetch -v -- origin stderr: 'fatal: detected dubious ownership in repository at 'G:/SD-Zluda/stable-diffusion-webui-amdgpu/tmp/sd-webui-segment-anything''

### Steps to reproduce the problem

1, Open stable diffsuion
2, install any extension
3, Error

### What should have happened?

/

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-07-24-04-40.json](https://github.com/user-attachments/files/16357172/sysinfo-2024-07-24-04-40.json)

### Console logs

```Shell
G:\SD-Zluda\stable-diffusion-webui-amdgpu>git pull
Already up to date.
venv "G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: v1.9.3-amd-32-g67fdead6
Commit hash: 67fdead6280bfe1f37c466d5279d54344c6305cf
Using ZLUDA in C:\zluda
Skipping onnxruntime installation.
You are up to date with the most recent release.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --medvram-sdxl --update-check --skip-ort
Loading weights [23076e06d0] from G:\SD-Zluda\stable-diffusion-webui-amdgpu\models\Stable-diffusion\cyberrealistic_v42-inpainting.safetensors
Creating model from config: G:\SD-Zluda\stable-diffusion-webui-amdgpu\configs\v1-inpainting-inference.yaml
G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.9s (prepare environment: 15.8s, initialize shared: 1.1s, other imports: 0.6s, load scripts: 0.6s, create ui: 0.8s, gradio launch: 0.3s).
Applying attention optimization: Doggettx... done.
Model loaded in 4.2s (load weights from disk: 0.4s, create model: 0.8s, apply weights to model: 2.0s, load textual inversion embeddings: 0.2s, calculate empty prompt: 0.5s).
*** Error completing request
*** Arguments: ('https://github.com/continue-revolution/sd-webui-segment-anything.git', ['ads', 'localization', 'installed'], 0, 'mask') {}
    Traceback (most recent call last):
      File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\modules\ui_extensions.py", line 400, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\modules\ui_extensions.py", line 371, in install_extension_from_url
        repo.remote().fetch()
      File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\git\remote.py", line 1015, in fetch
        res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
      File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\git\remote.py", line 854, in _get_fetch_info_from_stderr
        proc.wait(stderr=stderr_text)
      File "G:\SD-Zluda\stable-diffusion-webui-amdgpu\venv\lib\site-packages\git\cmd.py", line 604, in wait
        raise GitCommandError(remove_password_if_present(self.args), status, errstr)
    git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
      cmdline: git fetch -v -- origin
      stderr: 'fatal: detected dubious ownership in repository at 'G:/SD-Zluda/stable-diffusion-webui-amdgpu/tmp/sd-webui-segment-anything''
```

### Additional information

I have the latest of evertything installed

**Comment by VeteranXT** [comment]
Delete Veniv and redownload.

**Comment by CS1o** [comment]
Try deleting the content of the tmp folder inside the stable-diffusion-webui-amdgpu folder.
Then install the extension again.
