### ISSUE TITLE
[Bug]: cant generate arts

### ISSUE THREAD

**Issue by DELTER1235** [lshqqytiger/stable-diffusion-webui-amdgpu#510]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

when I tried to generate art, an error appeared instead of art
![image](https://github.com/user-attachments/assets/1bc8e141-274d-4f6d-b007-b478f61765f6)

### Steps to reproduce the problem

1. Download the current SD version at the time of writing this report
2. Edit webui-user.bat by adding set COMMANDLINE_ARGS= --opt-sub-quad-attention --lowvram --disable-nan-check --skip-torch-cuda-test --skip-ort
3. After the first unsuccessful launch, change the file to the following path: 'stable-diffusion-webui-amdgpuvenvScriptsactivate.bat' at the very bottom of this file add the following: pip uninstall onnxruntime onnxruntime-gpu -y
pip install onnxruntime
4. Successfully launch SD and try to generate an image

### What should have happened?

The image will be generated normally

### Sysinfo

[sysinfo.txt](https://github.com/user-attachments/files/16430702/sysinfo.txt)

### Console logs

```Shell
Found existing installation: onnxruntime 1.18.1
Uninstalling onnxruntime-1.18.1:
  Successfully uninstalled onnxruntime-1.18.1
WARNING: Skipping onnxruntime-gpu as it is not installed.
Collecting onnxruntime
  Using cached onnxruntime-1.18.1-cp310-cp310-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: coloredlogs in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from onnxruntime) (15.0.1)
Requirement already satisfied: flatbuffers in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from onnxruntime) (24.3.25)
Requirement already satisfied: numpy<2.0,>=1.21.6 in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from onnxruntime) (1.26.2)
Requirement already satisfied: packaging in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from onnxruntime) (24.1)
Requirement already satisfied: protobuf in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from onnxruntime) (3.20.0)
Requirement already satisfied: sympy in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from onnxruntime) (1.13.1)
Requirement already satisfied: humanfriendly>=9.1 in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from coloredlogs->onnxruntime) (10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from sympy->onnxruntime) (1.3.0)
Requirement already satisfied: pyreadline3 in d:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime) (3.4.1)
Using cached onnxruntime-1.18.1-cp310-cp310-win_amd64.whl (5.6 MB)
Installing collected packages: onnxruntime
Successfully installed onnxruntime-1.18.1
venv "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-2-g395ce8dc
Commit hash: 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
Skipping onnxruntime installation.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --opt-sub-quad-attention --lowvram --disable-nan-check --skip-torch-cuda-test --skip-ort
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
Loading weights [0e4a654468] from D:\stabily diff\stable-diffusion-webui-amdgpu\models\Stable-diffusion\Anime Style.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 39.1s (prepare environment: 62.2s, initialize shared: 0.7s, other imports: 2.9s, load scripts: 1.5s, initialize extra networks: 0.2s, create ui: 1.4s, gradio launch: 0.8s).
Creating model from config: D:\stabily diff\stable-diffusion-webui-amdgpu\configs\v1-inference.yaml
D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Applying attention optimization: sub-quadratic... done.
Model loaded in 21.8s (load weights from disk: 8.8s, create model: 1.2s, apply weights to model: 1.0s, calculate empty prompt: 10.6s).
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
*** Error completing request
*** Arguments: ('task(u9hbmzrc82a2m24)', <gradio.routes.Request object at 0x00000145A18925F0>, 'women with blue hair', '', [], 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', 'Use same scheduler', '', '', [], 0, 20, 'DPM++ 2M', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\txt2img.py", line 109, in txt2img
        processed = processing.process_images(p)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\processing.py", line 849, in process_images
        res = process_images_inner(p)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\processing.py", line 1082, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\processing.py", line 1440, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_samplers_kdiffusion.py", line 233, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_samplers_common.py", line 272, in launch_sampling
        return func()
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_samplers_kdiffusion.py", line 233, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_samplers_cfg_denoiser.py", line 249, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict(cond_in, image_cond_in))
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_hijack_utils.py", line 22, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_hijack_utils.py", line 34, in __call__
        return self.__sub_func(self.__orig_func, *args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_hijack_unet.py", line 50, in apply_model
        result = orig_func(self, x_noisy.to(devices.dtype_unet), t.to(devices.dtype_unet), cond, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_hijack_utils.py", line 22, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_hijack_utils.py", line 36, in __call__
        return self.__orig_func(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\modules\sd_unet.py", line 91, in UNetModel_forward
        return original_forward(self, x, timesteps, context, *args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1582, in _call_impl
        result = forward_call(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 86, in forward
        x = layer(x)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
        return forward_call(*args, **kwargs)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\extensions-builtin\Lora\networks.py", line 599, in network_Conv2d_forward
        return originals.Conv2d_forward(self, input)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
        return self._conv_forward(input, self.weight, self.bias)
      File "D:\stabily diff\stable-diffusion-webui-amdgpu\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
        return F.conv2d(input, weight, bias, self.stride,
    RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

---
```

### Additional information

I have a radeon rx 560 series video card and an AMD Ryzen 3 1200 Quad-Core Processor

**Comment by lshqqytiger** [comment]
Please remove `--skip-torch-cuda-test` if you want GPU to be used.
Instead, add `--use-directml`.
(remove venv folder to reinstall torch)

**Comment by DELTER1235** [comment]
> Please remove `--skip-torch-cuda-test` if you want GPU to be used. Instead, add `--use-directml`. (remove venv folder to reinstall torch)


This helped, thank you very much, I've been trying to install DS for a week
