### ISSUE TITLE
[Bug]: Clean Setup is broken. Configs wont download.

### ISSUE THREAD

**Issue by CS1o** [lshqqytiger/stable-diffusion-webui-amdgpu#533]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After a User tried to get the webui working with Zluda following my guide. He wasnt able to switch to an sdxl model, as it always time out.
I then did a reinstall for me to test if i get the same errors as him.

The Clean install first breaks as no base model could be downloaded. Thats because Runwayml deletet their 1.5-ema-pruned.safetensor and other models from their Huggingface Page.

After you input any 1.5 model and restart and select it, the errors begin. The webui starts to download a phantom model.safetensor, it wont be in the models folder.

When selecting a sdxl/pony model it starts to download a 10gb copen clip file. That wasnt the case before.

Most errors have to do with a huggingface url its not able to find:
`HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json`
and this interesting line:
`Failed to create model quickly; will retry using slow method.`

I guess its missing the config file that tells the webui how to load models properly.

At the bottom you see the full log with a lot of HTTP 401 errors.

### Steps to reproduce the problem

Git clone the webui for amd gpus.
use the --use-zluda --skip-ort --update-check cmd args
See the errors. Input a custom model into models/stable-diffusion
Get a lot of errors when loading the model.

### What should have happened?

The Webui should have worked like it did earlier where the base model got downloaded automaticly and more important the config.json files downloads worked.
Maybe you have to ship them with the webui now, if they are not available on huggingface anymore.

### Sysinfo

Windows 10 22H2
AMD Adrenalin 24.8.1
ROCm HIP SDK 6.1 and ZLUDA
AMD RX 7900XTX

### Console logs

```Shell
venv "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1-amd-5-gd8b7380b
Commit hash: d8b7380b18d044d2ee38695c58bae3a786689cf3
Using ZLUDA in D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\.zluda
Skipping onnxruntime installation.
You are up to date with the most recent release.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --update-check --skip-ort
Loading weights [879db523c3] from D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\models\Stable-diffusion\dreamshaper_8.safetensors
Creating model from config: D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\configs\v1-inference.yaml
creating model quickly: OSError
Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1854, in _raise_on_head_call_error
    raise head_call_error
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
Running on local URL:  http://127.0.0.1:7860
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66da1108-5c6e48023ad1d1b877cdee31;18b45ca2-5f34-4276-adf4-c4f1b9e87f14)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\shared_items.py", line 190, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 831, in load_model
    sd_model = instantiate_from_config(sd_config.model, state_dict)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 775, in instantiate_from_config
    return constructor(**params)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 104, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_disable_initialization.py", line 68, in CLIPTextModel_from_pretrained
    res = self.CLIPTextModel_from_pretrained(None, *model_args, config=pretrained_model_name_or_path, state_dict={}, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\modeling_utils.py", line 3213, in from_pretrained
    resolved_config_file = cached_file(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\utils\hub.py", line 425, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Failed to create model quickly; will retry using slow method.

To create a public link, set `share=True` in `launch()`.
Startup time: 9.4s (prepare environment: 11.5s, initialize shared: 1.5s, other imports: 0.5s, load scripts: 0.4s, create ui: 0.5s, gradio launch: 0.3s).
Applying attention optimization: Doggettx... done.
Model loaded in 3.3s (load weights from disk: 0.2s, create model: 1.2s, apply weights to model: 1.2s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.4s).
Reusing loaded model dreamshaper_8.safetensors [879db523c3] to load novaAnimeXL_ponyV20.safetensors
Calculating sha256 for D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\models\Stable-diffusion\novaAnimeXL_ponyV20.safetensors: d983234f5f4d7a59acf79dd07587936944d584d3f9ace3a5a03475409e3f391f
Loading weights [d983234f5f] from D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\models\Stable-diffusion\novaAnimeXL_ponyV20.safetensors
Creating model from config: D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\generative-models\configs\inference\sd_xl_base.yaml
creating model quickly: OSError
Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1854, in _raise_on_head_call_error
    raise head_call_error
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66da111e-6df8b5ae557de75a05e6fe90;fe20998b-078d-44b6-b71f-d68f5d230e8d)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\ui_settings.py", line 316, in <lambda>
    fn=lambda value, k=k: self.run_settings_single(value, key=k),
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\ui_settings.py", line 95, in run_settings_single
    if value is None or not opts.set(key, value):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\options.py", line 165, in set
    option.onchange()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\call_queue.py", line 14, in f
    res = func(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\initialize_util.py", line 181, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: sd_models.reload_model_weights()), call=False)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 992, in reload_model_weights
    load_model(checkpoint_info, already_loaded_state_dict=state_dict)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 831, in load_model
    sd_model = instantiate_from_config(sd_config.model, state_dict)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 775, in instantiate_from_config
    return constructor(**params)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\generative-models\sgm\models\diffusion.py", line 61, in __init__
    self.conditioner = instantiate_from_config(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\generative-models\sgm\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\generative-models\sgm\modules\encoders\modules.py", line 88, in __init__
    embedder = instantiate_from_config(embconfig)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\generative-models\sgm\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\generative-models\sgm\modules\encoders\modules.py", line 361, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_disable_initialization.py", line 68, in CLIPTextModel_from_pretrained
    res = self.CLIPTextModel_from_pretrained(None, *model_args, config=pretrained_model_name_or_path, state_dict={}, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\modeling_utils.py", line 3213, in from_pretrained
    resolved_config_file = cached_file(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\utils\hub.py", line 425, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Failed to create model quickly; will retry using slow method.
open_clip_pytorch_model.bin:  42%|████████████████████▎                           | 4.31G/10.2G [13:11<14:33, 6.70MB/s]
```

### Additional information

Getting this when loading up with an 1.5 model and then also switching to an 1.5 model:
```
venv "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1-amd-5-gd8b7380b
Commit hash: d8b7380b18d044d2ee38695c58bae3a786689cf3
Using ZLUDA in D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\.zluda
Skipping onnxruntime installation.
You are up to date with the most recent release.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --update-check --skip-ort
Loading weights [879db523c3] from D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\models\Stable-diffusion\dreamshaper_8.safetensors
Creating model from config: D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\configs\v1-inference.yaml
creating model quickly: OSError
Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1347, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1854, in _raise_on_head_call_error
    raise head_call_error
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66da18c0-0756de14105942065129b5e6;06fc8dd2-8bcb-4271-a61f-9296d5aed292)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\webyo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\shared_items.py", line 190, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 831, in load_model
    sd_model = instantiate_from_config(sd_config.model, state_dict)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 775, in instantiate_from_config
    return constructor(**params)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 104, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\sd_disable_initialization.py", line 68, in CLIPTextModel_from_pretrained
    res = self.CLIPTextModel_from_pretrained(None, *model_args, config=pretrained_model_name_or_path, state_dict={}, **kwargs)
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\modeling_utils.py", line 3213, in from_pretrained
    resolved_config_file = cached_file(
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\utils\hub.py", line 425, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Failed to create model quickly; will retry using slow method.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.7s (prepare environment: 12.3s, initialize shared: 1.4s, other imports: 0.5s, load scripts: 0.4s, create ui: 0.5s, gradio launch: 0.3s).
Applying attention optimization: Doggettx... done.
Model loaded in 3.1s (create model: 1.2s, apply weights to model: 1.2s, load textual inversion embeddings: 0.1s, calculate empty prompt: 0.4s).
Reusing loaded model dreamshaper_8.safetensors [879db523c3] to load photon_v1.safetensors
Calculating sha256 for D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\models\Stable-diffusion\photon_v1.safetensors: ec41bd2a8271acde4ae81cac004d9f3300e7fb0870eae8cbfe0bbc4ef8e27f91
Loading weights [ec41bd2a82] from D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\models\Stable-diffusion\photon_v1.safetensors
Applying attention optimization: Doggettx... done.
Weights loaded in 2.7s (send model to cpu: 0.7s, calculate hash: 1.4s, apply weights to model: 0.2s, move model to device: 0.4s).
```

**Comment by rickvalstar** [comment]
See my cross-post here: 

https://github.com/TheLastBen/fast-stable-diffusion/issues/2937#issuecomment-2484229424

I think it will solve the issue as it did for me.

Enjoy
