### ISSUE TITLE
[Bug]: Olive: Failed to load olive-ai: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by gwenmillett** [lshqqytiger/stable-diffusion-webui-amdgpu#541]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

cloned the git and ran the webui.bat file but I keep getting this error:
Olive: Failed to load olive-ai: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

### Steps to reproduce the problem

used CMD to clone the GIT for automatic installation and it came up with this error, the webui didn't open

### What should have happened?

webui should have opened

### What browsers do you use to access the UI ?

Brave

### Sysinfo

[sysinfo-2024-09-28-16-32.json](https://github.com/user-attachments/files/17175558/sysinfo-2024-09-28-16-32.json)

### Console logs

```Shell
venv "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
ROCm Toolkit was found.
==============================================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.11.5.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3106/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
Version: v1.7.0-amd-533-g25a3b6cb
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
Olive: Failed to load olive-ai: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\venv\Lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\launch.py", line 44, in main
    start()
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 663, in start
    import webui
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\modules\shared_init.py", line 62, in initialize
    initialize_onnx()
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\modules\onnx_impl\__init__.py", line 232, in initialize
    from .pipelines.onnx_stable_diffusion_pipeline import OnnxStableDiffusionPipeline
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\modules\onnx_impl\pipelines\__init__.py", line 7, in <module>
    import onnx
  File "C:\Users\Gwen\Documents\zluda\stable-diffusion-webui-amdgpu\venv\Lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
Press any key to continue . . .
```

### Additional information

I have an AMD  6950XT

**Comment by CS1o** [comment]
Hey, first you need to uninstall Python 3.12 as its not supported with Stable Diffusion Webuis.
Also dont git clone the repo into Documents, Desktop, or Downloads Folder. Your is currently in Documents. That can cause Permission errors.

Then if you want to use Zluda you can follow my Install Guide from here:
https://github.com/CS1o/Stable-Diffusion-Info/wiki/Webui-Installation-Guides

**Comment by pengan1987** [comment]
This bug occured since commit 15e09f1 , it's a confirmed bug of onnx 1.16.2: https://github.com/onnx/onnx/issues/6267
change `onnx==1.16.2` to `onnx==1.16.1` in `requirements.txt` and `requirements_versions.txt` to fix this problem.
