### ISSUE TITLE
[Bug]: (ZLUDA) Final step when processing in SD 1.0 takes longer than all previous steps combined

### ISSUE THREAD

**Issue by Spudsman2600** [lshqqytiger/stable-diffusion-webui-amdgpu#550]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

I realize this is somewhat similar to #502, but my experience is noticeably different.
Recently did a fresh install of A1111 with ZLUDA config (previously using DirectML) and saw a massive reduction in step time when generating images, but the final(?) step takes longer than all other steps combined before finishing. The image does eventually process, but the 'last' step takes longer than the normal experience with DirectML.

I'm on a full AMD setup with a Radeon VII (16GB VRAM), so when I was using DirectML I was getting around 10-12 seconds per iteration at 1024X1024. With ZLUDA, it appears I'm getting somewhere between 6-10 iterations per second (depending on checkpoint and LoRA usage), but then there's a very long hang before the process finishes. So, steps 1-19 will process in 2-3 seconds and then step 20 (or sometimes after step 20 is reported as 'finished') will take 3-4 minutes. I'm seeing 95-100% GPU usage (Compute1) during the last step, and if I have live previews enabled it's a little longer but the preview will only update once or twice. When processing with DirectML it would normally take 2-3 minutes with standard progression

I've tried different checkpoints, VAEs, as well as disabling live previews but I've seen no change in behavior. The strange thing is I don't see this with SDXL checkpoints. I get 2-3 iterations per second, steps proceed at a steady pace, and the final step isn't much different than the previous ones (30-40 seconds overall). That's incredible as I wasn't able to even load SDXL checkpoints before ZLUDA, but a lot of the LoRAs I prefer to use are for SD1 and I'd like to be able to use SD1 checkpoints when needed.

### Steps to reproduce the problem

1) Start A1111 with --use-zluda
2) Load a SD1 checkpoint, any VAE
3) Begin a Text2Img or Img2Img process at 1024x1024
4) see nearly all steps running at 5-10 iterations per second, progress bar fills in 2-3 seconds
5) see last step take 2-3 minutes while soaking the GPU
6) process finishes, provides image as expected

### What should have happened?

I would expect the final step to not take significantly longer than previous steps when using SD1 checkpoints, especially since SDXL checkpoints do not seem to have this issue.

### What browsers do you use to access the UI ?

Other

### Sysinfo

[sysinfo-2024-10-24-21-06.json](https://github.com/user-attachments/files/17515128/sysinfo-2024-10-24-21-06.json)

### Console logs

```Shell
venv "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1-amd-12-gae5ff7a2
Commit hash: ae5ff7a232cd898f653e4fffb36f507b54de8b72
Using ZLUDA in C:\SD-Zluda\a1111\stable-diffusion-webui-directml\.zluda
ROCm agents: ['gfx906:sramecc-:xnack-'], using gfx906:sramecc-:xnack-
Installing requirements
[Auto-Photoshop-SD] Attempting auto-update...
[Auto-Photoshop-SD] switch branch to extension branch.
checkout_result: Your branch is up to date with 'origin/master'.

[Auto-Photoshop-SD] Current Branch.
branch_result: * master

[Auto-Photoshop-SD] Fetch upstream.
fetch_result:
[Auto-Photoshop-SD] Pull upstream.
pull_result: Already up to date.
Installing requirements for diffusers
Requirement already satisfied: insightface==0.7.3 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from -r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (0.7.3)
Collecting onnx==1.14.0 (from -r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 2))
  Using cached onnx-1.14.0-cp310-cp310-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: onnxruntime==1.15.0 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from -r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: opencv-python==4.7.0.72 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from -r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 4)) (4.7.0.72)
Requirement already satisfied: ifnude in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from -r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 5)) (0.0.3)
Requirement already satisfied: cython in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from -r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 6)) (3.0.11)
Requirement already satisfied: numpy in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.26.2)
Requirement already satisfied: tqdm in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (4.66.5)
Requirement already satisfied: requests in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (2.32.3)
Requirement already satisfied: matplotlib in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (3.9.2)
Requirement already satisfied: Pillow in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: scipy in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.14.1)
Requirement already satisfied: scikit-learn in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.5.2)
Requirement already satisfied: scikit-image in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (0.21.0)
Requirement already satisfied: easydict in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.13)
Requirement already satisfied: albumentations in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.4.3)
Requirement already satisfied: prettytable in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (3.11.0)
Collecting protobuf>=3.20.2 (from onnx==1.14.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 2))
  Using cached protobuf-5.28.3-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from onnx==1.14.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 2)) (4.12.2)
Requirement already satisfied: coloredlogs in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (15.0.1)
Requirement already satisfied: flatbuffers in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (24.3.25)
Requirement already satisfied: packaging in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (24.1)
Requirement already satisfied: sympy in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (1.13.1)
Requirement already satisfied: opencv-python-headless>=4.5.1.48 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from ifnude->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 5)) (4.10.0.84)
Requirement already satisfied: PyYAML in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from albumentations->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (6.0.2)
Requirement already satisfied: networkx>=2.8 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (3.2.1)
Requirement already satisfied: imageio>=2.27 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (2.36.0)
Requirement already satisfied: tifffile>=2022.8.12 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (2024.9.20)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.7.0)
Requirement already satisfied: lazy_loader>=0.2 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from scikit-image->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (0.4)
Requirement already satisfied: joblib>=1.2.0 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from scikit-learn->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from scikit-learn->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (3.5.0)
Requirement already satisfied: humanfriendly>=9.1 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from coloredlogs->onnxruntime==1.15.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: cycler>=0.10 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from matplotlib->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: wcwidth in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from prettytable->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from requests->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from requests->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from requests->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from requests->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (2024.8.30)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from sympy->onnxruntime==1.15.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (1.3.0)
Requirement already satisfied: colorama in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from tqdm->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: pyreadline3 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime==1.15.0->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 3)) (3.5.4)
Requirement already satisfied: six>=1.5 in c:\sd-zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3->-r C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.16.0)
Using cached onnx-1.14.0-cp310-cp310-win_amd64.whl (13.3 MB)
Using cached protobuf-5.28.3-cp310-abi3-win_amd64.whl (431 kB)
Installing collected packages: protobuf, onnx
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.1
    Uninstalling protobuf-3.20.1:
      Successfully uninstalled protobuf-3.20.1
  Attempting uninstall: onnx
    Found existing installation: onnx 1.16.2
    Uninstalling onnx-1.16.2:
      Successfully uninstalled onnx-1.16.2
Successfully installed onnx-1.14.0 protobuf-5.28.3
C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda
No ROCm runtime is found, using ROCM_HOME='C:\Program Files\AMD\ROCm\5.7'
ONNX failed to initialize: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
Building PyTorch extensions using ROCm and Windows is not supported.
python_server_full_path:  C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
CHv1.8.11: Get Custom Model Folder
[-] ADetailer initialized. version: 24.9.0, num models: 10
CivitAI Browser+: Aria2 RPC started
2024-10-24 16:14:37,786 - roop - INFO - roop v0.0.2
2024-10-24 16:14:37,936 - roop - INFO - roop v0.0.2
Loading weights [6ce0161689] from C:\SD-Zluda\a1111\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\SD-Zluda\a1111\stable-diffusion-webui-directml\configs\v1-inference.yaml
CHv1.8.11: Set Proxy:
creating model quickly: OSError
Traceback (most recent call last):
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1484, in _raise_on_head_call_error
    raise head_call_error
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 301, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 454, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-671ab8be-2a4cdf0f0b47a4405505c709;d2ce9332-101d-404d-bbbd-4c245ea1e656)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\shared_items.py", line 190, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\sd_models.py", line 831, in load_model
    sd_model = instantiate_from_config(sd_config.model, state_dict)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\sd_models.py", line 775, in instantiate_from_config
    return constructor(**params)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\util.py", line 89, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 104, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\sd_disable_initialization.py", line 68, in CLIPTextModel_from_pretrained
    res = self.CLIPTextModel_from_pretrained(None, *model_args, config=pretrained_model_name_or_path, state_dict={}, **kwargs)
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\modeling_utils.py", line 3301, in from_pretrained
    resolved_config_file = cached_file(
  File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Failed to create model quickly; will retry using slow method.
C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\sd-webui-roop\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
*** Error executing callback ui_tabs_callback for C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\facechain\app.py", line 16, in <module>
        from facechain.inference_fact import GenPortrait
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\extensions\facechain\facechain\inference_fact.py", line 20, in <module>
        from modelscope.pipelines import pipeline
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\pipelines\__init__.py", line 4, in <module>
        from .base import Pipeline
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\pipelines\base.py", line 16, in <module>
        from modelscope.msdatasets import MsDataset
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\__init__.py", line 2, in <module>
        from modelscope.msdatasets.ms_dataset import MsDataset
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\ms_dataset.py", line 16, in <module>
        from modelscope.msdatasets.data_loader.data_loader_manager import (
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\data_loader\data_loader_manager.py", line 12, in <module>
        from modelscope.msdatasets.data_loader.data_loader import OssDownloader
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\data_loader\data_loader.py", line 15, in <module>
        from modelscope.msdatasets.data_files.data_files_manager import \
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\data_files\data_files_manager.py", line 11, in <module>
        from modelscope.msdatasets.download.dataset_builder import (
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\download\dataset_builder.py", line 24, in <module>
        from modelscope.msdatasets.download.download_manager import \
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\download\download_manager.py", line 9, in <module>
        from modelscope.msdatasets.utils.oss_utils import OssUtilities
      File "C:\SD-Zluda\a1111\stable-diffusion-webui-directml\venv\lib\site-packages\modelscope\msdatasets\utils\oss_utils.py", line 7, in <module>
        import oss2
    ModuleNotFoundError: No module named 'oss2'

---
[ERROR]: Config states C:\SD-Zluda\a1111\stable-diffusion-webui-directml\config_states\civitai_subfolders.json, "created_at" does not exist
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
COMMANDLINE_ARGS does not contain --api, API won't be mounted.
Startup time: 83.4s (prepare environment: 84.3s, initialize shared: 3.3s, other imports: 0.1s, list SD models: 0.2s, load scripts: 2.9s, create ui: 4.5s, gradio launch: 0.8s).
Applying attention optimization: Doggettx... done.
Model loaded in 8.8s (create model: 1.9s, apply weights to model: 4.5s, apply half(): 0.3s, move model to device: 0.1s, load textual inversion embeddings: 0.4s, calculate empty prompt: 1.5s).
100%|██████████████████████████████████████| 20/20 [00:23<00:00,  1.15s/it]
Total progress: 100%|██████████████████████| 20/20 [04:29<00:00, 13.47s/it]
Total progress: 100%|██████████████████████| 20/20 [04:29<00:00, 12.15it/s]
```

### Additional information

Installed latest AMD GPU drivers for Radeon VII
using ROCm 5.7
![Screenshot 2024-10-24 162058](https://github.com/user-attachments/assets/cfb5bf3b-bf83-4987-96e2-58f9f71d7097)
image attached is an example of GPU resource monitoring during the long 'final step' phase.

**Comment by CS1o** [comment]
Hey, first delete the roop extension as its outdated and causes errors in your log.
Then also update your other extensions.
Delete the venv folder and relaunch the webui-user.bat
If you want to Faceswap use the Reactor Extension or the standalone tool roop-unleashed.

And yes the bug you encounter is the same as in #502 . That bug only appears for 1.5 models and the cause is still unknown.
