### ISSUE TITLE
[Bug]: optimum.onnxruntime.modeling_diffusion has no attribute ORTPipelinePart

### ISSUE THREAD

**Issue by CS1o** [lshqqytiger/stable-diffusion-webui-amdgpu#555]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After the latest update of this webui fork and the forge-amdgpu fork, both wont launch anymore.
With or without --skip-ort doesnt make a difference.
See the Log.

### Steps to reproduce the problem

Update this webui or the forge fork and launch the webui-user.bat.

### What should have happened?

The webui should launch normaly.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

AMD Adrenalin 24.10.1
Windows 10 22H2
AMD RX 7900XTX & Ryzen 7 7800X3D

### Console logs

```Shell
Already up to date.
venv "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1-amd-15-gcf6c4e97
Commit hash: cf6c4e9765abe987e68a94006cf61672a076042c
ROCm: agents=['gfx1100', 'gfx1036']
ROCm: version=6.1, using agent gfx1100
ZLUDA support: experimental
Using ZLUDA in D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\.zluda
Skipping onnxruntime installation.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\a1111-sd-webui-tagcomplete':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\adetailer':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\sd-webui-animatediff':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\sd-webui-controlnet':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\sd-webui-cutoff':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\sd-webui-inpaint-background':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\sd-webui-mov2mov':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\sd-webui-reactor':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-depthmap-script':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-prompt-travel':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-rembg':
Already up to date.

Pulled changes for repository in 'D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\extensions\stable-diffusion-webui-wildcards':
Already up to date.

no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --skip-ort --update-all-extensions --ckpt-dir 'D:\Programme\AI-Zeug\stable-diffusion-webui-directml\models\Stable-diffusion' --lora-dir 'D:\Programme\AI-Zeug\stable-diffusion-webui-directml\models\Lora' --vae-dir 'D:\Programme\AI-Zeug\stable-diffusion-webui-directml\models\VAE' --esrgan-models-path 'D:\Programme\AI-Zeug\stable-diffusion-webui-directml\models\ESRGAN' --controlnet-dir 'D:\Programme\AI-Zeug\stable-diffusion-webui-directml\models\ControlNet'
Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\modules\launch_utils.py", line 712, in start
    import webui
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\modules\initialize.py", line 35, in imports
    from modules import shared_init
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\modules\shared_init.py", line 8, in <module>
    from modules.zluda import initialize_zluda
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\modules\zluda.py", line 7, in <module>
    from modules.onnx_impl.execution_providers import available_execution_providers, ExecutionProvider
  File "D:\Programme\AI-Zeug\SD-Zluda-Webui\stable-diffusion-webui-directml\modules\onnx_impl\__init__.py", line 192, in <module>
    def ORTDiffusionModelPart_to(self: optimum.onnxruntime.modeling_diffusion.ORTPipelinePart, *args, **kwargs):
AttributeError: module 'optimum.onnxruntime.modeling_diffusion' has no attribute 'ORTPipelinePart'
Drücken Sie eine beliebige Taste . . .
```

**Comment by CS1o** [comment]
Doesnt happen on a clean install or when you delete the venv folder and relaunch the webui-user.bat.

**Comment by Ael07** [comment]
Happened to me too, i stopped git pull updates and still working with pre-update version
optimum update is not working well with other dependencies

**Comment by lshqqytiger** [comment]
Closing as this no longer terminates process.
