### ISSUE TITLE
[Bug]: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

### ISSUE THREAD

**Issue by TheDarkPharoh** [lshqqytiger/stable-diffusion-webui-amdgpu#560]
### Checklist

- [ ] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I attempted to run webui-user.bat but it gave an error and stopped partway through. The error is something related to visual studio code

### Steps to reproduce the problem

Run webui-user.bat
Error occurs

### What should have happened?

It should have installed and started as normal

### What browsers do you use to access the UI ?

Other

### Sysinfo

I dont have this file as it never booted up

### Console logs

```Shell
Creating venv in directory C:\Users\esher\stable-diffusion-webui-directml\venv using python "C:\Users\esher\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe"
Requirement already satisfied: pip in c:\users\esher\stable-diffusion-webui-directml\venv\lib\site-packages (24.2)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Successfully installed pip-24.3.1
venv "C:\Users\esher\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
Version: v1.10.1-amd-16-g4730df18
Commit hash: 4730df185b557f1453a0f5f79ffd1fa7b36aae54
Installing torch and torchvision
Collecting torch==2.4.1
  Using cached torch-2.4.1-cp312-cp312-win_amd64.whl.metadata (27 kB)
Collecting torchvision
  Using cached torchvision-0.20.1-cp312-cp312-win_amd64.whl.metadata (6.2 kB)
Collecting torch-directml
  Using cached torch_directml-0.2.5.dev240914-cp312-cp312-win_amd64.whl.metadata (6.3 kB)
Collecting filelock (from torch==2.4.1)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.8.0 (from torch==2.4.1)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.4.1)
  Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.4.1)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch==2.4.1)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.4.1)
  Using cached fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting setuptools (from torch==2.4.1)
  Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
Collecting numpy (from torchvision)
  Using cached numpy-2.1.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision
  Using cached torchvision-0.20.0-cp312-cp312-win_amd64.whl.metadata (6.2 kB)
  Using cached torchvision-0.19.1-cp312-cp312-win_amd64.whl.metadata (6.1 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
  Using cached pillow-11.0.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.4.1)
  Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl.metadata (4.1 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.4.1)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.4.1-cp312-cp312-win_amd64.whl (199.4 MB)
Using cached torchvision-0.19.1-cp312-cp312-win_amd64.whl (1.3 MB)
Using cached torch_directml-0.2.5.dev240914-cp312-cp312-win_amd64.whl (9.0 MB)
Using cached pillow-11.0.0-cp312-cp312-win_amd64.whl (2.6 MB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
Using cached fsspec-2024.10.0-py3-none-any.whl (179 kB)
Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
Using cached numpy-2.1.3-cp312-cp312-win_amd64.whl (12.6 MB)
Using cached setuptools-75.3.0-py3-none-any.whl (1.3 MB)
Using cached sympy-1.13.3-py3-none-any.whl (6.2 MB)
Using cached MarkupSafe-3.0.2-cp312-cp312-win_amd64.whl (15 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, typing-extensions, sympy, setuptools, pillow, numpy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-3.0.2 filelock-3.16.1 fsspec-2024.10.0 jinja2-3.1.4 mpmath-1.3.0 networkx-3.4.2 numpy-2.1.3 pillow-11.0.0 setuptools-75.3.0 sympy-1.13.3 torch-2.4.1 torch-directml-0.2.5.dev240914 torchvision-0.19.1 typing-extensions-4.12.2
Installing clip
Installing open_clip
Installing requirements
Traceback (most recent call last):
  File "C:\Users\esher\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\esher\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\esher\stable-diffusion-webui-directml\modules\launch_utils.py", line 651, in prepare_environment
    run_pip(f'install -r "{requirements_file}"', "requirements")
  File "C:\Users\esher\stable-diffusion-webui-directml\modules\launch_utils.py", line 148, in run_pip
    return run(
           ^^^^
  File "C:\Users\esher\stable-diffusion-webui-directml\modules\launch_utils.py", line 120, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements.
Command: "C:\Users\esher\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Collecting setuptools==69.5.1 (from -r requirements_versions.txt (line 1))
  Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Collecting GitPython==3.1.32 (from -r requirements_versions.txt (line 2))
  Using cached GitPython-3.1.32-py3-none-any.whl.metadata (10.0 kB)
Collecting Pillow==9.5.0 (from -r requirements_versions.txt (line 3))
  Using cached Pillow-9.5.0-cp312-cp312-win_amd64.whl.metadata (9.7 kB)
Collecting accelerate==0.21.0 (from -r requirements_versions.txt (line 4))
  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
Collecting blendmodes==2022 (from -r requirements_versions.txt (line 5))
  Using cached blendmodes-2022-py3-none-any.whl.metadata (12 kB)
Collecting clean-fid==0.1.35 (from -r requirements_versions.txt (line 6))
  Using cached clean_fid-0.1.35-py3-none-any.whl.metadata (36 kB)
Collecting diffusers==0.30.2 (from -r requirements_versions.txt (line 7))
  Using cached diffusers-0.30.2-py3-none-any.whl.metadata (18 kB)
Collecting diskcache==5.6.3 (from -r requirements_versions.txt (line 8))
  Using cached diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting einops==0.4.1 (from -r requirements_versions.txt (line 9))
  Using cached einops-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting facexlib==0.3.0 (from -r requirements_versions.txt (line 10))
  Using cached facexlib-0.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting fastapi==0.94.0 (from -r requirements_versions.txt (line 11))
  Using cached fastapi-0.94.0-py3-none-any.whl.metadata (25 kB)
Collecting gradio==3.41.2 (from -r requirements_versions.txt (line 12))
  Using cached gradio-3.41.2-py3-none-any.whl.metadata (17 kB)
Collecting httpcore==0.15 (from -r requirements_versions.txt (line 13))
  Using cached httpcore-0.15.0-py3-none-any.whl.metadata (15 kB)
Collecting inflection==0.5.1 (from -r requirements_versions.txt (line 14))
  Using cached inflection-0.5.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting jsonmerge==1.8.0 (from -r requirements_versions.txt (line 15))
  Using cached jsonmerge-1.8.0.tar.gz (26 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting kornia==0.6.7 (from -r requirements_versions.txt (line 16))
  Using cached kornia-0.6.7-py2.py3-none-any.whl.metadata (12 kB)
Collecting lark==1.1.2 (from -r requirements_versions.txt (line 17))
  Using cached lark-1.1.2-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting numpy==1.26.2 (from -r requirements_versions.txt (line 18))
  Using cached numpy-1.26.2-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting omegaconf==2.2.3 (from -r requirements_versions.txt (line 19))
  Using cached omegaconf-2.2.3-py3-none-any.whl.metadata (3.9 kB)
Collecting open-clip-torch==2.20.0 (from -r requirements_versions.txt (line 20))
  Using cached open_clip_torch-2.20.0-py3-none-any.whl.metadata (46 kB)
Collecting onnx==1.16.2 (from -r requirements_versions.txt (line 21))
  Using cached onnx-1.16.2-cp312-cp312-win_amd64.whl.metadata (16 kB)
Collecting onnxruntime (from -r requirements_versions.txt (line 22))
  Using cached onnxruntime-1.20.0-cp312-cp312-win_amd64.whl.metadata (4.6 kB)
Collecting optimum (from -r requirements_versions.txt (line 23))
  Using cached optimum-1.23.3-py3-none-any.whl.metadata (20 kB)
Collecting olive-ai (from -r requirements_versions.txt (line 24))
  Using cached olive_ai-0.7.0-py3-none-any.whl.metadata (4.0 kB)
Collecting piexif==1.1.3 (from -r requirements_versions.txt (line 25))
  Using cached piexif-1.1.3-py2.py3-none-any.whl.metadata (3.7 kB)
Collecting protobuf==3.20.2 (from -r requirements_versions.txt (line 26))
  Using cached protobuf-3.20.2-py2.py3-none-any.whl.metadata (720 bytes)
Collecting psutil==5.9.5 (from -r requirements_versions.txt (line 27))
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl.metadata (21 kB)
Collecting pytorch_lightning==1.9.4 (from -r requirements_versions.txt (line 28))
  Using cached pytorch_lightning-1.9.4-py3-none-any.whl.metadata (22 kB)
Collecting resize-right==0.0.2 (from -r requirements_versions.txt (line 29))
  Using cached resize_right-0.0.2-py3-none-any.whl.metadata (551 bytes)
Collecting safetensors==0.4.2 (from -r requirements_versions.txt (line 30))
  Using cached safetensors-0.4.2-cp312-none-win_amd64.whl.metadata (3.9 kB)
Collecting scikit-image==0.21.0 (from -r requirements_versions.txt (line 31))
  Using cached scikit_image-0.21.0.tar.gz (22.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'

stderr:   error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [21 lines of output]
  + meson setup C:\Users\esher\AppData\Local\Temp\pip-install-mdaatrjy\scikit-image_1c43024d58954391b522f3618138e3f8 C:\Users\esher\AppData\Local\Temp\pip-install-mdaatrjy\scikit-image_1c43024d58954391b522f3618138e3f8\.mesonpy-64u34r8m -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\esher\AppData\Local\Temp\pip-install-mdaatrjy\scikit-image_1c43024d58954391b522f3618138e3f8\.mesonpy-64u34r8m\meson-python-native-file.ini
  The Meson build system
  Version: 1.6.0
  Source dir: C:\Users\esher\AppData\Local\Temp\pip-install-mdaatrjy\scikit-image_1c43024d58954391b522f3618138e3f8
  Build dir: C:\Users\esher\AppData\Local\Temp\pip-install-mdaatrjy\scikit-image_1c43024d58954391b522f3618138e3f8\.mesonpy-64u34r8m
  Build type: native build
  Project name: scikit-image
  Project version: 0.21.0
  WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

  ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
  The following exception(s) were encountered:
  Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
  Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
  Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
  Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
  Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
  Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
  Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

  A full log can be found at C:\Users\esher\AppData\Local\Temp\pip-install-mdaatrjy\scikit-image_1c43024d58954391b522f3618138e3f8\.mesonpy-64u34r8m\meson-logs\meson-log.txt
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Press any key to continue . . .
```

### Additional information

command args=--use-directml

**Comment by lshqqytiger** [comment]
Downgrade python to 3.11 or older. Python 3.12 is not supported.
