### ISSUE TITLE
[Bug]: I am not sure if I install correct or not, or should I continue doing it, --skip-torch-cuda-test appear

### ISSUE THREAD

**Issue by Darkrider000** [lshqqytiger/stable-diffusion-webui-amdgpu#562]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

So I do webui-user.bat --use-zluda on cmd like I should
then add --skip-torch-cuda-test happened
I knew this would happened using GMD, but what I am not sure is, is this supposed to happened even using --use zluda as well?
I haven't install HIP SDK yet due to I using RX 5700 so the way to install is more complex since I have to do ROCm 5.7.0  stuff from what I read a bit
but there seem a lot of step that make me wonder should I try doing all this or not since I found no mention of --skip-torch-cuda-test problem yet
I also already try pip cache purge and delete venv multiple time as well

### Steps to reproduce the problem

1. CMD and cd to file location
2. webui.user.bat --use-zluda
3. --skip-torch-cuda-test happened after install

### What should have happened?

--skip-torch-cuda-test not appear? I don't really know

### What browsers do you use to access the UI ?

Other

### Sysinfo

--dump-sysinfo not working

### Console logs

```Shell
Downloading MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl (15 kB)
Installing collected packages: tbb, mpmath, intel-openmp, typing-extensions, sympy, pillow, numpy, networkx, mkl, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision
Successfully installed MarkupSafe-3.0.2 filelock-3.16.1 fsspec-2024.10.0 intel-openmp-2021.4.0 jinja2-3.1.4 mkl-2021.4.0 mpmath-1.3.0 networkx-3.4.2 numpy-2.1.3 pillow-11.0.0 sympy-1.13.3 tbb-2021.13.1 torch-2.3.0+cu121 torchvision-0.18.0+cu121 typing-extensions-4.12.2
Traceback (most recent call last):
  File "C:\Users\Intel\Desktop\stable-diffusion-webui-amdgpu-1.10.0-amd\launch.py", line 48, in <module>
    main()
  File "C:\Users\Intel\Desktop\stable-diffusion-webui-amdgpu-1.10.0-amd\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\Intel\Desktop\stable-diffusion-webui-amdgpu-1.10.0-amd\modules\launch_utils.py", line 587, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
```

**Comment by lshqqytiger** [comment]
The installer installed torch compiled for cpu as no HIP SDK detected. Please install HIP SDK first.

**Comment by CS1o** [comment]
With a 5700XT you can install HIP SDK 6.1 and use ZLUDA.
For a complete Guide take a look here at the Automatic1111 with ZLUDA Guide:
https://github.com/CS1o/Stable-Diffusion-Info/wiki/Webui-Installation-Guides
