### ISSUE TITLE
[Bug]: ruwnayml/stable-diffusion-v1-5 does not longer exists

### ISSUE THREAD

**Issue by jaider** [lshqqytiger/stable-diffusion-webui-amdgpu#563]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When attempting to access the path for ruwnayml/stable-diffusion-v1-5, a 404 error is returned. This indicates that the resource or URL is no longer available on the server, meaning the specific model or library has been removed or moved to a different location. If you encounter this, you'll need to find an alternative source or repository for the model.
https://huggingface.co/runwayml/stable-diffusion-v1-5
Maybe as alternative we can use https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5? or stablediffusiontutorials/stable-diffusion-v1.5?

### Steps to reproduce the problem

When attempting to access the path for ruwnayml/stable-diffusion-v1-5, a 404 error is returned. 

### What should have happened?

Should found an stable-diffusion-v1-5 model

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

I have this error maybe related:
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/config.json

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1484, in _raise_on_head_call_error
    raise head_call_error
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 301, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\Users\Jaider\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 454, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6728fc43-1f73bcbd196f8c557752f211;1632e79d-41d9-4a86-9ba0-a656f2e8aa0b)
```

### Additional information

GPU AMD RX 7700XT

**Comment by jaider** [comment]
(duplicated) rel. https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/16459
